name: Channels
version: '${project.version}'
main: me.xxgradzix.channels.Channels
api-version: '1.17'

depend: [ WorldGuard ]

database: true

channels:
  myplugin:playercount:
    outbound: true
    inbound: true

commands:
  getInventory:

  channel:
    aliases:
      - ch
      - channels